import type { Category } from '../domain/types.js'

type CategorySeed = Pick<Category, 'id' | 'name' | 'type' | 'icon'> & { parentId?: string }

export const DEFAULT_CATEGORY_SEEDS: readonly CategorySeed[] = [
  { id: 'expense-food', name: 'Food', type: 'EXPENSE', icon: 'shopping-cart' },
  {
    id: 'expense-food-supermarket',
    name: 'Supermarket',
    type: 'EXPENSE',
    parentId: 'expense-food',
  },
  {
    id: 'expense-food-restaurants',
    name: 'Restaurants',
    type: 'EXPENSE',
    parentId: 'expense-food',
  },
  { id: 'expense-food-delivery', name: 'Delivery', type: 'EXPENSE', parentId: 'expense-food' },
  { id: 'expense-food-coffee', name: 'Coffee', type: 'EXPENSE', parentId: 'expense-food' },
  { id: 'expense-housing', name: 'Housing', type: 'EXPENSE', icon: 'home' },
  {
    id: 'expense-housing-electricity',
    name: 'Electricity',
    type: 'EXPENSE',
    parentId: 'expense-housing',
  },
  { id: 'expense-housing-water', name: 'Water', type: 'EXPENSE', parentId: 'expense-housing' },
  {
    id: 'expense-housing-internet',
    name: 'Internet',
    type: 'EXPENSE',
    parentId: 'expense-housing',
  },
  {
    id: 'expense-housing-maintenance',
    name: 'Maintenance',
    type: 'EXPENSE',
    parentId: 'expense-housing',
  },
  {
    id: 'expense-housing-furniture',
    name: 'Furniture',
    type: 'EXPENSE',
    parentId: 'expense-housing',
  },
  { id: 'expense-transport', name: 'Transport', type: 'EXPENSE', icon: 'car' },
  { id: 'expense-transport-fuel', name: 'Fuel', type: 'EXPENSE', parentId: 'expense-transport' },
  {
    id: 'expense-transport-service',
    name: 'Car service',
    type: 'EXPENSE',
    parentId: 'expense-transport',
  },
  {
    id: 'expense-transport-parking',
    name: 'Parking',
    type: 'EXPENSE',
    parentId: 'expense-transport',
  },
  { id: 'expense-transport-tolls', name: 'Tolls', type: 'EXPENSE', parentId: 'expense-transport' },
  { id: 'expense-transport-taxi', name: 'Taxi', type: 'EXPENSE', parentId: 'expense-transport' },
  { id: 'expense-children', name: 'Children', type: 'EXPENSE', icon: 'child' },
  {
    id: 'expense-children-clothing',
    name: 'Clothing',
    type: 'EXPENSE',
    parentId: 'expense-children',
  },
  {
    id: 'expense-children-activities',
    name: 'Activities',
    type: 'EXPENSE',
    parentId: 'expense-children',
  },
  { id: 'expense-children-school', name: 'School', type: 'EXPENSE', parentId: 'expense-children' },
  { id: 'expense-children-toys', name: 'Toys', type: 'EXPENSE', parentId: 'expense-children' },
  ...[
    'Health',
    'Entertainment',
    'Shopping',
    'Holidays',
    'Subscriptions',
    'Taxes',
    'Insurance',
    'Other',
  ].map((name) => ({ id: `expense-${name.toLowerCase()}`, name, type: 'EXPENSE' as const })),
  { id: 'income-salary', name: 'Salary', type: 'INCOME', icon: 'briefcase' },
  { id: 'income-freelance', name: 'Freelance', type: 'INCOME' },
  { id: 'income-business', name: 'Business income', type: 'INCOME' },
  { id: 'income-bonus', name: 'Bonus', type: 'INCOME' },
  { id: 'income-refund', name: 'Refund', type: 'INCOME' },
  { id: 'income-other', name: 'Other income', type: 'INCOME' },
  { id: 'expense-uncategorised', name: 'Uncategorised', type: 'EXPENSE' },
  { id: 'income-uncategorised', name: 'Uncategorised', type: 'INCOME' },
] as const
