import type {
  EmotionScenario,
  EmotionType,
  EverydayScenario,
  EverydayTopic,
  KidsDifficulty,
  LearningRelationship,
  SequenceDefinition,
} from '@family-expense-tracker/shared'

export interface IllustratedAsset {
  symbol: string
  color: string
  label?: string
  url?: string
}

export const ADVANCED_ASSETS = new Map<string, IllustratedAsset>()

function asset(id: string, symbol: string, label: string, color = '#eef7f4') {
  ADVANCED_ASSETS.set(id, { symbol, label, color })
  return id
}

function everyday(
  id: string,
  topic: EverydayTopic,
  narration: string,
  preferred: [string, string, string],
  other: [string, string, string],
  explanation: string,
  difficulty: KidsDifficulty = 1,
  third?: [string, string, string],
): EverydayScenario {
  const choices = [preferred, other, ...(third ? [third] : [])].map(
    ([choiceId, symbol, label]) => ({
      id: `${id}-${choiceId}`,
      assetId: asset(`${id}-${choiceId}-asset`, symbol, label),
      narration: label,
    }),
  )
  return {
    id,
    topic,
    narration,
    choices,
    preferredChoiceId: choices[0]!.id,
    explanationNarration: explanation,
    difficulty,
    enabled: true,
    origin: 'SYSTEM',
  }
}

export const SYSTEM_EVERYDAY_SCENARIOS: EverydayScenario[] = [
  everyday(
    'hands-before-food',
    'HYGIENE',
    'Τι κάνουμε πριν φάμε;',
    ['wash', '🧼', 'Πλένουμε τα χέρια'],
    ['shoes', '👟', 'Παίζουμε με τα παπούτσια'],
    'Πλένουμε τα χέρια πριν φάμε για να είναι καθαρά.',
  ),
  everyday(
    'hands-after-toilet',
    'HYGIENE',
    'Τι κάνουμε αφού πάμε στην τουαλέτα;',
    ['wash', '🧼', 'Πλένουμε τα χέρια'],
    ['run', '🏃', 'Τρέχουμε αμέσως'],
    'Μετά την τουαλέτα πλένουμε καλά τα χέρια μας.',
  ),
  everyday(
    'brush-teeth',
    'HYGIENE',
    'Τι κάνουμε για καθαρά δόντια;',
    ['brush', '🪥', 'Βουρτσίζουμε τα δόντια'],
    ['candy', '🍬', 'Τρώμε καραμέλα'],
    'Βουρτσίζουμε απαλά τα δόντια μας.',
  ),
  everyday(
    'cough-tissue',
    'HYGIENE',
    'Τι χρησιμοποιούμε όταν βήχουμε;',
    ['tissue', '🤧', 'Χαρτομάντιλο ή τον αγκώνα'],
    ['hand', '✋', 'Το χέρι προς τους άλλους'],
    'Βήχουμε στον αγκώνα ή σε χαρτομάντιλο.',
  ),
  everyday(
    'bath-time',
    'HYGIENE',
    'Τι βοηθά να καθαρίσουμε το σώμα μας;',
    ['bath', '🛁', 'Κάνουμε μπάνιο'],
    ['paint', '🎨', 'Βάζουμε μπογιές'],
    'Το μπάνιο και το νερό μάς βοηθούν να καθαριστούμε.',
  ),
  everyday(
    'dirty-clothes',
    'HYGIENE',
    'Πού βάζουμε τα λερωμένα ρούχα;',
    ['laundry', '🧺', 'Στο καλάθι των ρούχων'],
    ['floor', '⬇️', 'Στο πάτωμα'],
    'Τα λερωμένα ρούχα μπαίνουν στο καλάθι.',
  ),
  everyday(
    'ask-toy',
    'KINDNESS',
    'Θέλουμε το παιχνίδι ενός φίλου. Τι κάνουμε;',
    ['ask', '🙋', 'Το ζητάμε'],
    ['grab', '✊', 'Το αρπάζουμε'],
    'Ζητάμε το παιχνίδι και περιμένουμε τη σειρά μας.',
  ),
  everyday(
    'take-turns',
    'KINDNESS',
    'Δύο παιδιά θέλουν την κούνια. Τι μπορούν να κάνουν;',
    ['turns', '🔄', 'Παίζουν με τη σειρά'],
    ['push', '🫸', 'Σπρώχνουν'],
    'Μπορούν να παίξουν ήρεμα με τη σειρά.',
  ),
  everyday(
    'say-thanks',
    'KINDNESS',
    'Κάποιος μας βοηθά. Τι μπορούμε να πούμε;',
    ['thanks', '💛', 'Ευχαριστώ'],
    ['nothing', '🤐', 'Δεν λέμε τίποτα'],
    'Μπορούμε να πούμε ευχαριστώ.',
  ),
  everyday(
    'help-pick-up',
    'KINDNESS',
    'Έπεσαν οι κάρτες ενός φίλου. Τι μπορούμε να κάνουμε;',
    ['help', '🤝', 'Βοηθάμε να τις μαζέψει'],
    ['leave', '🚶', 'Φεύγουμε'],
    'Μπορούμε να βοηθήσουμε να μαζευτούν οι κάρτες.',
  ),
  everyday(
    'gentle-hands',
    'SOCIAL',
    'Πώς αγγίζουμε τους φίλους μας;',
    ['gentle', '👐', 'Με απαλά χέρια'],
    ['rough', '💥', 'Με δυνατά σπρωξίματα'],
    'Χρησιμοποιούμε απαλά χέρια.',
  ),
  everyday(
    'listen-friend',
    'SOCIAL',
    'Ο φίλος μας μιλά. Τι κάνουμε;',
    ['listen', '👂', 'Ακούμε'],
    ['shout', '📣', 'Φωνάζουμε πιο δυνατά'],
    'Ακούμε όσο ο άλλος μιλά.',
  ),
  everyday(
    'share-blocks',
    'SOCIAL',
    'Έχουμε πολλά τουβλάκια. Τι μπορούμε να κάνουμε;',
    ['share', '🧱🧱', 'Δίνουμε μερικά στον φίλο'],
    ['hide', '🙈', 'Τα κρύβουμε όλα'],
    'Όταν έχουμε αρκετά, μπορούμε να μοιραστούμε.',
  ),
  everyday(
    'comfort-sad-friend',
    'KINDNESS',
    'Ο φίλος μας είναι στενοχωρημένος. Τι μπορούμε να κάνουμε;',
    ['comfort', '🤝💛', 'Μένουμε κοντά και προσφέρουμε βοήθεια'],
    ['hide', '🙈🧸', 'Κρύβουμε το παιχνίδι'],
    'Μπορούμε να μείνουμε κοντά και να προσφέρουμε βοήθεια.',
    2,
  ),
  everyday(
    'tidy-toys',
    'HOME',
    'Τελειώσαμε το παιχνίδι. Πού βάζουμε τα παιχνίδια;',
    ['box', '🧸📦', 'Στο κουτί τους'],
    ['stairs', '🪜', 'Στη σκάλα'],
    'Βάζουμε τα παιχνίδια στη θέση τους.',
  ),
  everyday(
    'books-shelf',
    'HOME',
    'Πού βάζουμε τα βιβλία;',
    ['shelf', '📚', 'Στο ράφι'],
    ['sink', '🚰', 'Στον νεροχύτη'],
    'Τα βιβλία μένουν στο ράφι.',
  ),
  everyday(
    'rubbish-bin',
    'HOME',
    'Πού βάζουμε ένα άδειο χαρτάκι;',
    ['bin', '🗑️', 'Στον κάδο'],
    ['sofa', '🛋️', 'Στον καναπέ'],
    'Τα σκουπίδια μπαίνουν στον κάδο.',
  ),
  everyday(
    'food-table',
    'FOOD',
    'Πού τρώμε το φαγητό;',
    ['table', '🍽️', 'Στο τραπέζι'],
    ['floor', '🧸', 'Στο πάτωμα με τα παιχνίδια'],
    'Το φαγητό μένει στο τραπέζι.',
  ),
  everyday(
    'pajamas-bed',
    'ROUTINE',
    'Τι φοράμε πριν κοιμηθούμε;',
    ['pajamas', '🛌', 'Τις πιτζάμες'],
    ['coat', '🧥', 'Το παλτό'],
    'Πριν τον ύπνο φοράμε τις πιτζάμες μας.',
  ),
  everyday(
    'morning-dress',
    'ROUTINE',
    'Ξυπνήσαμε. Τι κάνουμε πριν βγούμε;',
    ['dress', '👕', 'Ντυνόμαστε'],
    ['sleep', '😴', 'Κοιμόμαστε με τα παπούτσια'],
    'Το πρωί ντυνόμαστε πριν φύγουμε.',
  ),
  everyday(
    'road-hand',
    'SAFETY',
    'Είμαστε κοντά στον δρόμο. Τι κάνουμε;',
    ['hand', '🤝', 'Κρατάμε το χέρι του μεγάλου'],
    ['run', '🏃', 'Τρέχουμε μόνοι'],
    'Κοντά στον δρόμο κρατάμε το χέρι ενός μεγάλου.',
  ),
  everyday(
    'bike-helmet',
    'SAFETY',
    'Τι φοράμε στο ποδήλατο ή στο πατίνι;',
    ['helmet', '⛑️', 'Κράνος'],
    ['hat', '🎩', 'Καπέλο παιχνιδιού'],
    'Το κράνος προστατεύει το κεφάλι μας.',
  ),
  everyday(
    'car-seat',
    'SAFETY',
    'Πώς καθόμαστε στο αυτοκίνητο;',
    ['belt', '🪑', 'Στο παιδικό κάθισμα με ζώνη'],
    ['stand', '🧍', 'Όρθιοι'],
    'Καθόμαστε στο παιδικό κάθισμα με τη ζώνη.',
  ),
  everyday(
    'hot-stove',
    'SAFETY',
    'Η κουζίνα είναι ζεστή. Τι κάνουμε;',
    ['adult', '🙋', 'Μένουμε πίσω και φωνάζουμε μεγάλο'],
    ['touch', '🔥', 'Την αγγίζουμε'],
    'Δεν αγγίζουμε τη ζεστή κουζίνα. Ζητάμε βοήθεια.',
  ),
  everyday(
    'unknown-medicine',
    'SAFETY',
    'Βρήκαμε ένα άγνωστο φάρμακο. Τι κάνουμε;',
    ['ask', '🧑', 'Ρωτάμε έναν μεγάλο'],
    ['taste', '💊', 'Το δοκιμάζουμε'],
    'Δεν αγγίζουμε άγνωστα φάρμακα. Ρωτάμε έναν μεγάλο.',
  ),
  everyday(
    'wet-floor',
    'SAFETY',
    'Το πάτωμα είναι βρεγμένο. Πώς περπατάμε;',
    ['slow', '🚶', 'Αργά και προσεκτικά'],
    ['run', '🏃', 'Τρέχοντας'],
    'Στο βρεγμένο πάτωμα περπατάμε προσεκτικά.',
  ),
  everyday(
    'gentle-pet',
    'ANIMALS',
    'Πώς χαϊδεύουμε ένα ζωάκι;',
    ['gentle', '🐶🤲', 'Απαλά'],
    ['tail', '🐕', 'Τραβάμε την ουρά'],
    'Αγγίζουμε τα ζωάκια απαλά.',
  ),
  everyday(
    'pet-eating',
    'ANIMALS',
    'Το ζωάκι τρώει. Τι κάνουμε;',
    ['quiet', '🐶🍽️', 'Το αφήνουμε ήσυχο'],
    ['touch', '✋', 'Πειράζουμε το φαγητό του'],
    'Αφήνουμε το ζωάκι ήσυχο όσο τρώει.',
  ),
  everyday(
    'unknown-dog',
    'ANIMALS',
    'Βλέπουμε ένα σκυλάκι που δεν γνωρίζουμε. Τι κάνουμε;',
    ['ask', '🙋🐕', 'Ρωτάμε πρώτα τον μεγάλο'],
    ['run', '🏃🐕', 'Τρέχουμε να το αγκαλιάσουμε'],
    'Ρωτάμε έναν μεγάλο πριν πλησιάσουμε άγνωστο ζωάκι.',
  ),
]

function sequence(
  id: string,
  title: string,
  icons: string[],
  labels: string[],
  category: string,
  difficulty: KidsDifficulty = 1,
): SequenceDefinition {
  return {
    id,
    title,
    steps: icons.map((symbol, index) => ({
      id: `${id}-step-${index + 1}`,
      assetId: asset(`${id}-asset-${index + 1}`, symbol, labels[index]!),
      narration: labels[index]!,
    })),
    narration: 'Τι έρχεται μετά;',
    explanationNarration: `Πρώτα ${labels[0]}, μετά ${labels[1]}, και στο τέλος ${labels.at(-1)}.`,
    difficulty,
    category,
    enabled: true,
    origin: 'SYSTEM',
  }
}

export const SYSTEM_SEQUENCES: SequenceDefinition[] = [
  sequence(
    'seed-flower',
    'Από τον σπόρο στο λουλούδι',
    ['🌰', '🌱', '🌼'],
    ['ο σπόρος', 'το φυτό', 'το λουλούδι'],
    'NATURE',
  ),
  sequence(
    'egg-bird',
    'Από το αυγό στο πουλί',
    ['🥚', '🐣', '🐦'],
    ['το αυγό', 'το πουλάκι βγαίνει', 'το πουλί'],
    'ANIMALS',
  ),
  sequence(
    'dirty-clean-hands',
    'Καθαρά χέρια',
    ['👐', '🧼', '✨👐'],
    ['λερωμένα χέρια', 'πλένουμε', 'καθαρά χέρια'],
    'HYGIENE',
  ),
  sequence(
    'wake-leave',
    'Το πρωί',
    ['🌅', '👕', '🚪'],
    ['ξυπνάμε', 'ντυνόμαστε', 'φεύγουμε από το σπίτι'],
    'ROUTINE',
  ),
  sequence(
    'cloud-puddle',
    'Η βροχή',
    ['🌧️', '🌦️', '💧'],
    ['το σύννεφο', 'η βροχή', 'η λακκούβα'],
    'NATURE',
  ),
  sequence(
    'banana-snack',
    'Ετοιμάζω μπανάνα',
    ['🍌', '🔪', '🍌🍽️'],
    ['η μπανάνα', 'ο μεγάλος την κόβει', 'η μπανάνα στο πιάτο'],
    'FOOD',
  ),
  sequence(
    'blocks-tower',
    'Ο πύργος',
    ['🧱', '🧱🧱', '🏰'],
    ['ένα τουβλάκι', 'πολλά τουβλάκια', 'ο πύργος'],
    'PLAY',
  ),
  sequence(
    'wash-clothes',
    'Πλένουμε ρούχα',
    ['👕', '🫧', '☀️👕'],
    ['τα λερωμένα ρούχα', 'το πλύσιμο', 'τα καθαρά ρούχα'],
    'HOME',
  ),
  sequence(
    'bread-toast',
    'Φρυγανισμένο ψωμί',
    ['🍞', '♨️', '🍞✨'],
    ['το ψωμί', 'ο μεγάλος το ζεσταίνει', 'το φρυγανισμένο ψωμί'],
    'FOOD',
  ),
  sequence(
    'ice-water',
    'Ο πάγος λιώνει',
    ['🧊', '☀️', '💧'],
    ['ο πάγος', 'ζεσταίνεται', 'το νερό'],
    'NATURE',
    2,
  ),
  sequence(
    'caterpillar-butterfly',
    'Η πεταλούδα',
    ['🐛', '🛌', '🦋'],
    ['η κάμπια', 'το κουκούλι', 'η πεταλούδα'],
    'ANIMALS',
    2,
  ),
  sequence(
    'paint-picture',
    'Ζωγραφίζω',
    ['📄', '🖍️', '🖼️'],
    ['το χαρτί', 'ζωγραφίζουμε', 'η ζωγραφιά'],
    'PLAY',
  ),
  sequence(
    'toys-away',
    'Μαζεύω παιχνίδια',
    ['🧸', '🙌', '📦'],
    ['τα παιχνίδια έξω', 'τα μαζεύουμε', 'τα παιχνίδια στο κουτί'],
    'HOME',
  ),
  sequence(
    'meal-cleanup',
    'Μετά το φαγητό',
    ['🍽️', '😋', '🧽'],
    ['το φαγητό', 'τρώμε', 'μαζεύουμε το τραπέζι'],
    'ROUTINE',
  ),
  sequence(
    'sunset-bed',
    'Ώρα για ύπνο',
    ['🌇', '🪥', '🛌'],
    ['βραδιάζει', 'βουρτσίζουμε δόντια', 'κοιμόμαστε'],
    'ROUTINE',
  ),
  sequence(
    'snowman',
    'Ο χιονάνθρωπος',
    ['❄️', '⛄', '☀️💧'],
    ['το χιόνι', 'ο χιονάνθρωπος', 'ο ήλιος τον λιώνει'],
    'NATURE',
    2,
  ),
]

const emotionIcons: Record<EmotionType, string> = {
  HAPPY: '🙂',
  SAD: '😢',
  ANGRY: '😠',
  SCARED: '😨',
  SURPRISED: '😮',
  TIRED: '😴',
}

function emotion(
  id: string,
  scene: string,
  narration: string,
  expected: EmotionType,
  alternatives: EmotionType[],
  explanation: string,
  difficulty: KidsDifficulty = 1,
): EmotionScenario {
  return {
    id,
    sceneAssetId: asset(`${id}-scene`, scene, narration, '#fff2d9'),
    narration,
    options: [expected, ...alternatives],
    expectedEmotion: expected,
    explanationNarration: explanation,
    difficulty,
    enabled: true,
    origin: 'SYSTEM',
  }
}

export const EMOTION_ASSETS = new Map(
  Object.entries(emotionIcons).map(([id, symbol]) => [
    `emotion-${id.toLowerCase()}`,
    { symbol, label: id, color: '#f8efff' },
  ]),
)

export const SYSTEM_EMOTION_SCENARIOS: EmotionScenario[] = [
  emotion(
    'gift-happy',
    '🎁🙂',
    'Το παιδί παίρνει το δώρο που ήθελε. Πώς νιώθει;',
    'HAPPY',
    ['SAD'],
    'Χαίρεται για το δώρο του.',
  ),
  emotion(
    'icecream-sad',
    '🍦⬇️😢',
    'Το παγωτό του παιδιού έπεσε. Πώς νιώθει;',
    'SAD',
    ['HAPPY'],
    'Στενοχωριέται που έπεσε το παγωτό.',
  ),
  emotion(
    'balloon-surprised',
    '🎈💥😮',
    'Ένα μπαλόνι έσκασε ξαφνικά, αλλά όλοι είναι ασφαλείς. Πώς νιώθει;',
    'SURPRISED',
    ['TIRED'],
    'Ο ξαφνικός ήχος το έκανε να εκπλαγεί.',
  ),
  emotion(
    'dark-scared',
    '🌙😨',
    'Το δωμάτιο σκοτείνιασε ξαφνικά. Πώς νιώθει το παιδί;',
    'SCARED',
    ['HAPPY'],
    'Μπορεί να φοβήθηκε από το ξαφνικό σκοτάδι.',
  ),
  emotion(
    'bed-tired',
    '🛌😴',
    'Το παιδί χασμουριέται πριν τον ύπνο. Πώς νιώθει;',
    'TIRED',
    ['ANGRY'],
    'Χασμουριέται γιατί είναι κουρασμένο.',
  ),
  emotion(
    'tower-falls-angry',
    '🧱💥😠',
    'Ο πύργος που έφτιαχνε έπεσε. Πώς νιώθει;',
    'ANGRY',
    ['HAPPY'],
    'Θύμωσε επειδή χάλασε ο πύργος.',
  ),
  emotion(
    'friend-arrives-happy',
    '👋🙂',
    'Έφτασε ένας αγαπημένος φίλος. Πώς νιώθει;',
    'HAPPY',
    ['TIRED'],
    'Χαίρεται που βλέπει τον φίλο του.',
  ),
  emotion(
    'toy-lost-sad',
    '🧸❓😢',
    'Το αγαπημένο παιχνίδι δεν βρίσκεται. Πώς νιώθει;',
    'SAD',
    ['SURPRISED'],
    'Στενοχωριέται που δεν βρίσκει το παιχνίδι.',
  ),
  emotion(
    'thunder-scared',
    '⛈️😨',
    'Ακούστηκε δυνατή βροντή. Πώς νιώθει;',
    'SCARED',
    ['HAPPY'],
    'Ο δυνατός ήχος μπορεί να το φόβισε.',
  ),
  emotion(
    'cake-surprise',
    '🎂😮',
    'Οι φίλοι έφεραν ξαφνικά μια τούρτα. Πώς νιώθει;',
    'SURPRISED',
    ['SAD'],
    'Δεν περίμενε την τούρτα και εκπλήχθηκε.',
  ),
  emotion(
    'long-day-tired',
    '🌆😴',
    'Μετά από μια μεγάλη μέρα το παιδί τρίβει τα μάτια. Πώς νιώθει;',
    'TIRED',
    ['HAPPY'],
    'Τα μάτια του δείχνουν ότι νυστάζει.',
  ),
  emotion(
    'turn-wait-angry',
    '⏳😠',
    'Το παιδί πρέπει να περιμένει κι άλλο για τη σειρά του. Πώς νιώθει;',
    'ANGRY',
    ['TIRED'],
    'Μπορεί να θύμωσε που περιμένει.',
  ),
  emotion(
    'family-picnic-happy',
    '🧺🙂',
    'Η οικογένεια παίζει μαζί στο πάρκο. Πώς νιώθει;',
    'HAPPY',
    ['SCARED', 'SAD'],
    'Περνά όμορφα μαζί με την οικογένεια.',
    2,
  ),
  emotion(
    'broken-crayon-sad',
    '🖍️💔😢',
    'Η αγαπημένη κηρομπογιά έσπασε. Πώς νιώθει;',
    'SAD',
    ['HAPPY', 'TIRED'],
    'Στενοχωριέται που έσπασε η κηρομπογιά.',
    2,
  ),
  emotion(
    'dog-bark-scared',
    '🐕📣😨',
    'Ένα άγνωστο σκυλί γάβγισε δυνατά από μακριά. Πώς νιώθει;',
    'SCARED',
    ['HAPPY', 'TIRED'],
    'Ο δυνατός ήχος μπορεί να το φόβισε.',
    2,
  ),
  emotion(
    'new-room-surprised',
    '🚪✨😮',
    'Ανοίγει την πόρτα και βλέπει ένα δωμάτιο γεμάτο μπαλόνια. Πώς νιώθει;',
    'SURPRISED',
    ['SAD', 'TIRED'],
    'Δεν περίμενε τα μπαλόνια.',
    2,
  ),
  emotion(
    'nap-tired',
    '☀️🛋️😴',
    'Το παιδί ξαπλώνει και κλείνει τα μάτια το μεσημέρι. Πώς νιώθει;',
    'TIRED',
    ['ANGRY', 'SURPRISED'],
    'Χρειάζεται ξεκούραση.',
    2,
  ),
  emotion(
    'snatched-toy-angry',
    '🧸😠',
    'Κάποιος πήρε απότομα το παιχνίδι χωρίς να ρωτήσει. Πώς νιώθει;',
    'ANGRY',
    ['HAPPY', 'TIRED'],
    'Μπορεί να θύμωσε που πήραν το παιχνίδι απότομα.',
    2,
  ),
]

export const SYSTEM_CLASSIFICATION_RELATIONSHIPS: LearningRelationship[] = [
  {
    id: 'class-toothbrush-bathroom',
    sourceCardId: 'toothbrush',
    targetCardId: 'bathroom',
    type: 'BELONGS_IN',
    narration: 'Η οδοντόβουρτσα ανήκει στο μπάνιο.',
  },
  {
    id: 'class-milk-fridge',
    sourceCardId: 'milk',
    targetCardId: 'refrigerator',
    type: 'STORED_IN',
    narration: 'Το γάλα φυλάσσεται στο ψυγείο.',
  },
  {
    id: 'class-spoon-kitchen',
    sourceCardId: 'spoon',
    targetCardId: 'kitchen',
    type: 'BELONGS_IN',
    narration: 'Το κουτάλι ανήκει στην κουζίνα.',
  },
  {
    id: 'class-bed-bedroom',
    sourceCardId: 'bed',
    targetCardId: 'bedroom',
    type: 'BELONGS_IN',
    narration: 'Το κρεβάτι ανήκει στο υπνοδωμάτιο.',
  },
  {
    id: 'class-shirt-wardrobe',
    sourceCardId: 'shirt',
    targetCardId: 'wardrobe',
    type: 'STORED_IN',
    narration: 'Η μπλούζα φυλάσσεται στην ντουλάπα.',
  },
  {
    id: 'class-fish-water',
    sourceCardId: 'fish',
    targetCardId: 'water-place',
    type: 'LIVES_IN',
    narration: 'Το ψάρι ζει στο νερό.',
  },
  {
    id: 'class-cow-farm',
    sourceCardId: 'cow',
    targetCardId: 'farm',
    type: 'LIVES_IN',
    narration: 'Η αγελάδα ζει στη φάρμα.',
  },
  {
    id: 'class-shoe-feet',
    sourceCardId: 'shoe',
    targetCardId: 'feet-place',
    type: 'WORN_ON',
    narration: 'Το παπούτσι φοριέται στο πόδι.',
  },
  {
    id: 'class-hat-head',
    sourceCardId: 'hat',
    targetCardId: 'head-place',
    type: 'WORN_ON',
    narration: 'Το καπέλο φοριέται στο κεφάλι.',
  },
  {
    id: 'class-coat-wardrobe',
    sourceCardId: 'coat',
    targetCardId: 'wardrobe',
    type: 'STORED_IN',
    narration: 'Το παλτό φυλάσσεται στην ντουλάπα.',
  },
  {
    id: 'class-egg-fridge',
    sourceCardId: 'egg',
    targetCardId: 'refrigerator',
    type: 'STORED_IN',
    narration: 'Τα αυγά φυλάσσονται στο ψυγείο.',
  },
  {
    id: 'class-bowl-kitchen',
    sourceCardId: 'bowl',
    targetCardId: 'kitchen',
    type: 'BELONGS_IN',
    narration: 'Το μπολ ανήκει στην κουζίνα.',
  },
]

export const CLASSIFICATION_DESTINATIONS = new Map<string, IllustratedAsset>([
  ['bathroom', { symbol: '🛁', label: 'το μπάνιο', color: '#dff3ff' }],
  ['refrigerator', { symbol: '🧊', label: 'το ψυγείο', color: '#e8f5ff' }],
  ['kitchen', { symbol: '🍽️', label: 'η κουζίνα', color: '#fff3dc' }],
  ['bedroom', { symbol: '🛏️', label: 'το υπνοδωμάτιο', color: '#f1e8ff' }],
  ['wardrobe', { symbol: '🚪👕', label: 'η ντουλάπα', color: '#f6ecdf' }],
  ['water-place', { symbol: '🌊', label: 'το νερό', color: '#dff3ff' }],
  ['farm', { symbol: '🚜', label: 'η φάρμα', color: '#e8f3dc' }],
  ['feet-place', { symbol: '🦶', label: 'το πόδι', color: '#ffede4' }],
  ['head-place', { symbol: '🙂', label: 'το κεφάλι', color: '#ffede4' }],
  ['bookshelf', { symbol: '📚', label: 'η βιβλιοθήκη', color: '#f6ecdf' }],
])

export const SYSTEM_CONTENT_VERSION = 2
